# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nat24h_activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='single',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activitysubscription',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nat24h_activity.Activity'),
        ),
        migrations.AddField(
            model_name='activitysubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
